package com.example.symphonysearch

import android.app.Application
import com.example.symphonysearch.data.MyObjectBox
import io.objectbox.BoxStore

class SymphonySearchApp : Application() {
    lateinit var boxStore: BoxStore
        private set

    override fun onCreate() {
        super.onCreate()
        
        // MyObjectBox is generated by ObjectBox after the first build
        boxStore = MyObjectBox.builder()
            .androidContext(this)
            .build()
    }
}
